#version 450

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) readonly buffer input_blob
{ float input_data[]; };
layout(binding = 1) readonly buffer pre_blob
{ float pre_data[]; };
layout(binding = 2) writeonly buffer output_blob
{ float output_data[]; };

layout(push_constant) uniform parameter
{
    uint hidden_size;
    uint multiplier;
}
p;

void main()
{
    const uint column = gl_GlobalInvocationID.x;
    const uint row = gl_GlobalInvocationID.y;
    if (column >= p.hidden_size)
        return;
    float value = 0.0;
    for (uint copy = 0; copy < p.multiplier; ++copy)
        value += input_data[(row * p.multiplier + copy) * p.hidden_size + column] * pre_data[row * p.multiplier + copy];
    output_data[row * p.hidden_size + column] = value;
}
