#!/usr/bin/env python3
"""Generate private tokenizer tables from pinned Unicode 9, 16 and 17 UCD files.

The source directory must contain ucd9/UnicodeData.txt,
ucd9/DerivedNormalizationProps.txt, ucd16/UnicodeData.txt and
ucd17/UnicodeData.txt from https://www.unicode.org/Public/.
Run: python tools/generate_unicode.py /path/to/ucd-sources
Only maintainers regenerate this header; building the runtime needs no Python,
network access, Unicode library or data files. Input checksums pin the versions.
"""

from __future__ import annotations

import argparse
import array
import hashlib
from pathlib import Path


def read_data(path: Path) -> tuple[bytearray, bytearray, dict[int, tuple[int, ...]]]:
    categories = bytearray(0x110000)
    combining = bytearray(0x110000)
    decompositions: dict[int, tuple[int, ...]] = {}
    first = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        cp = int(fields[0], 16)
        category = fields[2]
        flags = {"L": 1, "M": 2, "N": 4, "P": 8, "S": 16}.get(category[0], 0)
        if category in {"Lu", "Lt"}:
            flags |= 32
        if category == "Ll":
            flags |= 64
        if fields[1].endswith(", First>"):
            first = cp
            continue
        begin = first if fields[1].endswith(", Last>") else cp
        categories[begin:cp + 1] = bytes([flags]) * (cp + 1 - begin)
        combining[begin:cp + 1] = bytes([int(fields[3])]) * (cp + 1 - begin)
        if fields[5] and not fields[5].startswith("<"):
            decompositions[cp] = tuple(int(value, 16) for value in fields[5].split())
    for begin, end in ((9, 13), (32, 32), (0x85, 0x85), (0xa0, 0xa0), (0x1680, 0x1680),
                       (0x2000, 0x200a), (0x2028, 0x2029), (0x202f, 0x202f), (0x205f, 0x205f), (0x3000, 0x3000)):
        for cp in range(begin, end + 1):
            categories[cp] |= 128
    return categories, combining, decompositions


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    args = parser.parse_args()
    source = args.source
    paths = [source / f"ucd{version}" / "UnicodeData.txt" for version in (9, 16, 17)]
    exclusions_path = source / "ucd9" / "DerivedNormalizationProps.txt"
    checksums = (
        "68dfc414d28257b9b5d6ddbb8b466c768c00ebdf6cbf7784364a9b6cad55ee8f",
        "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
        "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
        "02d8e12cea7c61a9f3cc5fbf8eaceadf8da23fe83d60c64cf647088830b810cc",
    )
    for path, checksum in zip(paths + [exclusions_path], checksums):
        if hashlib.sha256(path.read_bytes()).hexdigest() != checksum:
            raise ValueError(f"Unicode data checksum mismatch: {path}")
    _, combining, decompositions = read_data(paths[0])
    cat16, _, _ = read_data(paths[1])
    cat17, _, _ = read_data(paths[2])
    properties = array.array("I", (a | b << 8 | c << 16 for a, b, c in zip(cat16, cat17, combining)))
    exclusions: set[int] = set()
    for line in exclusions_path.read_text(encoding="utf-8").splitlines():
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) < 2:
            continue
        bounds = [int(value, 16) for value in fields[0].strip().split("..")]
        if fields[1].strip() == "Full_Composition_Exclusion":
            exclusions.update(range(bounds[0], bounds[-1] + 1))
        if fields[1].strip() == "NFC_QC" and fields[2].strip() in {"N", "M"}:
            for cp in range(bounds[0], bounds[-1] + 1):
                properties[cp] |= 0x1000000
    ranges = [(cp - 1, properties[cp - 1]) for cp in range(1, len(properties)) if properties[cp] != properties[cp - 1]]
    ranges.append((len(properties) - 1, properties[-1]))
    assert all(1 <= len(value) <= 2 for value in decompositions.values())
    compositions = sorted(((value[0] << 21) | value[1], cp) for cp, value in decompositions.items()
                          if len(value) == 2 and cp not in exclusions)
    assert min(pair & 0x1fffff for pair, _ in compositions) == 0x300
    lines = [
        "// Generated by tools/generate_unicode.py; do not edit.",
        "// Unicode 16/17 character categories and Unicode 9 NFC data.",
        "// See unicode.LICENSE for the Unicode Data Files license.",
    ]
    for path in paths + [exclusions_path]:
        lines.append(f"// {path.parent.name}/{path.name} SHA-256: {hashlib.sha256(path.read_bytes()).hexdigest()}")
    lines += [
        "#ifndef NCNN_MOE_MODELS_UNICODEDATA_H", "#define NCNN_MOE_MODELS_UNICODEDATA_H", "", "#include <cstdint>", "",
        "namespace ncnn {", "namespace moe {", "",
        "enum UnicodeProperty : uint32_t", "{",
        "    UnicodeLetter = 1,", "    UnicodeMark = 2,", "    UnicodeNumber = 4,", "    UnicodePunctuation = 8,",
        "    UnicodeSymbol = 16,", "    UnicodeUpper = 32,", "    UnicodeLower = 64,", "    UnicodeSpace = 128,",
        "    UnicodeNfcCheck = 0x1000000", "};", "",
        "// Packed bytes: Unicode 16 categories, Unicode 17 categories, Unicode 9 combining class, NFC quick check.",
        "struct UnicodeRange", "{", "    uint32_t end;", "    uint32_t properties;", "};", "",
        "struct UnicodeDecomposition", "{", "    uint32_t codepoint;", "    uint32_t first;", "    uint32_t second;", "};", "",
        "struct UnicodeComposition", "{", "    uint64_t pair;", "    uint32_t codepoint;", "};", "",
        "static const uint32_t unicode_ascii[] = {",
    ]
    lines += [f"    0x{value:x}," for value in properties[:128]]
    lines += ["};", "", "static const UnicodeRange unicode_ranges[] = {"]
    lines += [f"    {{0x{cp:x}, 0x{value:x}}}," for cp, value in ranges]
    lines += ["};", "", "static const UnicodeDecomposition unicode_decompositions[] = {"]
    lines += [f"    {{0x{cp:x}, 0x{value[0]:x}, 0x{value[1] if len(value) == 2 else 0:x}}}," for cp, value in sorted(decompositions.items())]
    lines += ["};", "", "static const UnicodeComposition unicode_compositions[] = {"]
    lines += [f"    {{0x{pair:x}ULL, 0x{cp:x}}}," for pair, cp in compositions]
    lines += ["};", "", "} // namespace moe", "} // namespace ncnn", "", "#endif // NCNN_MOE_MODELS_UNICODEDATA_H", ""]
    destination = Path(__file__).resolve().parents[1] / "src/models/unicodedata.h"
    destination.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(ranges)} property ranges, {len(decompositions)} decompositions, {len(compositions)} compositions: {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
